language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"

env:
  - NO_INTERACTION=1 TEST_TIMEOUT=120 LIBRABBITMQ_VERSION=master
  - PHP_AMQP_VERSION=master

services:
  rabbitmq

before_script:
  # install librabbitmq C library (required by php-amqp)
  - sh -c "git clone git://github.com/alanxz/rabbitmq-c.git"
  - sh -c "cd rabbitmq-c && git checkout ${LIBRABBITMQ_VERSION}"
  - sh -c "cd rabbitmq-c && autoreconf -i && ./configure && make && sudo make install"
  # install php-amqp extension
  - sh -c "git clone git://github.com/pdezwart/php-amqp.git"
  - sh -c "cd php-amqp && git checkout ${PHP_AMQP_VERSION}"
  - sh -c "cd php-amqp && phpize && ./configure && make && sudo make install"
  # get PSR-0 autoloader
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar --dev install

script: phpunit --coverage-text --configuration ./tests/phpunit.xml
