language: php

php:
  - "5.5"
#  - "5.4"
#  - "5.3"
#  - "5.2"

env:
  # stable
#  - NO_INTERACTION=1 TEST_TIMEOUT=120 LIBRABBITMQ_VERSION="rabbitmq-c-v0.3.0" PHP_AMQP_VERSION="v1.0.9"
  # master
  - NO_INTERACTION=1 TEST_TIMEOUT=120 LIBRABBITMQ_VERSION=master PHP_AMQP_VERSION=master

services:
  rabbitmq

before_script:
  # install librabbitmq C library (required by php-amqp)
  - sh -c "git clone git://github.com/alanxz/rabbitmq-c.git"
  - sh -c "cd rabbitmq-c && git checkout ${LIBRABBITMQ_VERSION}"
  - sh -c "cd rabbitmq-c && cmake -DBUILD_EXAMPLES=No -DBUILD_TOOLS=No -DBUILD_TESTS=No ."
  - sh -c "cd rabbitmq-c && make && sudo make install"
  # install php-amqp extension
  - sh -c "git clone git://github.com/pdezwart/php-amqp.git"
  - sh -c "cd php-amqp && git checkout ${PHP_AMQP_VERSION}"
  - sh -c "cd php-amqp && phpize && ./configure && make && sudo make install"
  # add amqp extension to php.ini
  - sh -c "echo \"extension=amqp.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`"
  # get PSR-0 autoloader
  - sh -c "curl -s http://getcomposer.org/installer | php --"
  - sh -c "php composer.phar --dev install"

script: phpunit --coverage-text --configuration ./tests/phpunit.xml

notify:
  - email
